-- generated by DBA setup, do not edit this file manually
-- (C) 2024 Michael Lindenau licensed via https://www.gnu.org/licenses/agpl-3.0.txt and https://toent.ch/licenses/AI_DISCLOSURE_LICENSE_V1
-- Not allowed to be used as AI training material without explicite permission.

DEFINE OTAP_USER="OTAP"
DEFINE OTAP_TABLESPACE="OTAP_TABLESPACE"
DEFINE OTAP_ROLE="OTAP_USER"
DEFINE ROLE_CREATOR="SYS"
